version: '3.4'

services:
  dockerwebbapp:
    image: dockerwebbapp
    build:
      context: .
      dockerfile: src/dockerwebbapp/Dockerfile
    ports:
      - 80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ~/.vsdbg:/remote_debugger
